version: 2.1

environment:
  PYTHONPATH: /home/circleci/project/src
  
executors:
  python-program-executor:
    docker:
      - image: "circleci/python:3.6.4"

jobs:
  build:
    executor: python-program-executor
    working_directory: ~/Stevens
    steps:
      - checkout
      - run: |
          # python -m pip install --upgrade pip
          # python -m pip install requests
          python hw_04a_Refactor_YujunKong_SSW567.py

workflows:
  build_and_test:
    jobs:
      - build
