version: 2.1

executors:
  python-program-executor:
    docker:
      - image: "circleci/python:3.6.4"

jobs:
  build:
    executor: python-program-executor
    working_directory: ~/Stevens
    steps:
      - checkout
      - run: |
          python hw_04a_Refactor_YujunKong_SSW567.py

workflows:
  my-custom-workflow:
    jobs:
      - build
