version: 2.1

orbs:
  python: circleci/python@2.0.3
  heroku: circleci/heroku@1.2.6
  
jobs: 
  build:
    working_directory: ~/Stevens
    docker: 
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: -m pip install requests
      - run: python hw_04a_Refactor_YujunKong_SSW567.py
      
workflows:
  build_and_test:
    jobs:
      - build
