version: 2.1
  
executors:
  python-program-executor:
    docker:
      - image: "circleci/python:3.9.0"

jobs:
  build:
    executor: python-program-executor
    steps:
      - checkout
      - run: |          
          python hw_04a_YujunKong_SSW567.py

workflows:
  build_and_test:
    jobs:
      - build
