version: 2.1
  
executors:
  python-program-executor:
    docker:
      - image: "circleci/python:3.9.0"

jobs:
  build:
    working_directory: ~/Stevens
    executor: python-program-executor
    steps:
      - checkout
      - run: python ~/app/Stevens/Majoring/SSW-567_A/Assignments/Homework_04_A/hw_04a_YujunKong_SSW567.py

workflows:
  build_and_test:
    jobs:
      - build
