version: 2.1
  
executors:
  python-program-executor:
    docker:
      - image: "circleci/python:3.9.0"

jobs:
  # Homework 02 A
  build_hw_02-A:
    executor: python-program-executor
    steps:
      - checkout
      - run:
          name: "building"
          working_directory: ~/project/Majoring/SSW-567_A/Assignments/Homework_02_A
          command: |
            python Triangle_Fixed.py
  test_hw_02-A:
    executor: python-program-executor
    steps:
      - checkout
      - run:
          name: "testing"
          working_directory: ~/project/Majoring/SSW-567_A/Assignments/Homework_02_A
          command: |
            python -m unittest -v TestTriangle_Fixed.py
  
  # Homework 04 A, Updated to Homework 05 A - Mocking the service of GitHub REST APIs
  build_hw_04-A:
    executor: python-program-executor
    steps:
      - checkout
      - run:
          name: "building"
          working_directory: ~/project/Majoring/SSW-567_A/Assignments/Homework_04_A
          command: |
            python hw_04a_ykong_ssw567.py
  test_hw_04-A:
    executor: python-program-executor
    steps:
      - checkout
      - run:
          name: "testing"
          working_directory: ~/project/Majoring/SSW-567_A/Assignments/Homework_04_A
          command: |
            python -m unittest -v hw_04a_test_ykong_ssw567.py
            
workflows:
  build_and_test:
    jobs:    
      - build_hw_02-A:
          filters:
            branches:
              only: HW05a_Mocking
      - test_hw_02-A:
          requires:
            - build_hw_02-A
            
      - build_hw_04-A:
          filters:
            branches:
              only: HW05a_Mocking
      - test_hw_04-A:
          requires:
            - build_hw_04-A
