version: 2.1
  
executors:
  python-program-executor:
    docker:
      - image: "circleci/python:3.9.0"

jobs:
  executor: python-program-executor

  test:
    steps:
      - checkout
      - run:
          name: "testing"
          working_directory: ~/project/Majoring/SSW-567_A/Assignments/Homework_04_A
          command: |
            python -m unittest -v hw_04a_test_YujunKong_SSW567.py
            
workflows:
  build_and_test:
    jobs:
      
      - test

